Adding server experiment, see how to use go test for our benchmarking

diff --git a/go/Makefile b/go/Makefile
--- a/go/Makefile
+++ b/go/Makefile
@@ -5,7 +5,7 @@ PROF=./prof
 # GO=go1.18
 GO=go1.22.0
 
-PROG=havlakgo1 havlakgo2 havlakgo3 havlakgo4 revcmpgo gcgo1 gcgo2 recmat1 itmat1
+PROG=havlakgo1 havlakgo2 havlakgo3 havlakgo4 revcmpgo gcgo1 gcgo2 recmat1 itmat1 md mdpgo
 
 all: $(PROG)
 
@@ -45,6 +45,16 @@ itmat1:
 recmat1:
 	cd recmat1 && $(GO) build -o ../bin/recmat1 
 
+md:
+	cd markdown && $(GO) build -o ../bin/md 
+
+mdpgo:
+	@if [ "$(GO)" != "go1.22.0" ]; then \
+		echo "Error: change Go compiler to version 1.22.0"; \
+		exit 1; \
+	fi
+	cd markdown && $(GO) build -pgo=auto -o ../bin/mdpgo
+	
 %.cprof: 
 	$(MAKE) $*
 	$(BIN)/$* -cpuprofile=$(PROF)/$@
@@ -73,4 +83,4 @@ clean:
 clean-prof:
 	rm -f $(PROF)/*
 
-.PHONY: all havlakgo revcmpgo itmat1 recmat1 clean
+.PHONY: all havlakgo revcmpgo itmat1 recmat1 md mdpgo clean
